services:
  - type: web
    name: my-web-app
    env: node
      - type: web
    name: my-backend
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --force-reinstall numpy==1.26.4 --no-cache-dir
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    runtime: python
    branch: main
    autoDeploy: true
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: my-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    runtime: python
    branch: main
    autoDeploy: true
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production

